In [ ]:
print("hello world")

In [2]:
! pip install scikit-learn numpy pandas

  Using cached numpy-2.0.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
  Using cached pandas-2.2.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (19 kB)
  Using cached scipy-1.14.0-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 13.4 MB/s eta 0:00:0000:0100:01
Using cached numpy-2.0.1-cp312-cp312-macosx_14_0_arm64.whl (5.0 MB)
Using cached pandas-2.2.2-cp312-cp312-macosx_11_0_arm64.whl (11.3 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Us

In [3]:
import os
! pip install kaggle

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.7/82.7 kB 1.5 MB/s eta 0:00:00a 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 5.5 MB/s eta 0:00:00
  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
  Using cached charset_normalizer-3.3.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (33 kB)
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.0/163.0 kB 3.9 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.8/162.8 kB 12.1 MB/s eta 0:00:00
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached urllib3-2.2.2-py3-none-any.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 12.7 MB/s eta 0:00:00
Using cached charset_normalizer-3.3.2-cp312-cp312-macosx_11_

In [4]:
filename = 'breast-cancer-wisconsin-data.zip'
os.makedirs("classification", exist_ok=True)
for root, dirs, file in os.walk("./", topdown=True):
    if filename in file:
        break
else:
    !kaggle datasets download -d uciml/breast-cancer-wisconsin-data
    !mv breast-cancer-wisconsin-data.zip 'classification/'

Dataset URL: https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data
License(s): CC-BY-NC-SA-4.0
100%|███████████████████████████████████████| 48.6k/48.6k [00:00<00:00, 403kB/s]
100%|███████████████████████████████████████| 48.6k/48.6k [00:00<00:00, 397kB/s]


In [5]:
for root, dirs, file in os.walk("./", topdown=True):
    if 'data.csv' in file:
        break
else:
    !unzip classification/breast-cancer-wisconsin-data.zip -d classification/

Archive:  classification/breast-cancer-wisconsin-data.zip
  inflating: classification/data.csv  


In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

ModuleNotFoundError: No module named 'pandas'

In [7]:
pip install pandas

  Using cached pandas-2.2.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (19 kB)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.2-cp312-cp312-macosx_11_0_arm64.whl (11.3 MB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [10]:
data = "./classification/data.csv"
df = pd.read_csv(data)

#Display first few ewos
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [12]:
#Basic Information About Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [13]:
# Display summary statistics
print("Display summary statistics: \n",df.describe())

Display summary statistics: 
                  id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0

In [14]:
#Check for missing values

print("missing value:\n", df.isnull().sum())

missing value:
 id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst

In [15]:
#Drop columns which are null

df = df.drop(['Unnamed: 32', 'id'], axis = 1)

#Change M to 1, B to 0 in diagnosis column

X = df.drop('diagnosis', axis=1)  
y = df['diagnosis']     

# Convert 'diagnosis' column to binary
y = y.replace({'M': 1, 'B': 0})

print("target: \n",y.head(10))

target: 
 0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
Name: diagnosis, dtype: int64


/var/folders/xz/6390rdvs3974jqvyrm7x_kqm0000gn/T/ipykernel_98221/688082910.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = y.replace({'M': 1, 'B': 0})


In [16]:
from sklearn.model_selection import train_test_split

# Split the data into training, validation, and test sets (70%, 10%, 20%)
# Data split 70-30 as training and temp. the 30% of temp is further split to validation and test
#random state can be anything
#X is attribute, y is label
# either validatoin or test can be used for testing in this case but usually only test
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.66, random_state=42)

# Check the shapes of the splits
X_train.shape, X_val.shape, X_test.shape



#the 30 generated is the number of columns -- the attributes

((398, 30), (58, 30), (113, 30))

In [23]:
#even when uses name LogisticRegression its not part of regression its part of classification
#doesnt do hard classification, gives probability curve

log_reg = LogisticRegression(max_iter=10000)
log_reg.fit(X_train, y_train)

metrics = {
    'Model': ['Logistic Regression'],
    'Accuracy': [accuracy_score(y_val, log_reg.predict(X_val))],
    'Precision': [precision_score(y_val, log_reg.predict(X_val)),],
    'Recall': [recall_score(y_val, log_reg.predict(X_val))],
    'F1-Score': [f1_score(y_val, log_reg.predict(X_val))]
}

metrics_df = pd.DataFrame(metrics)
metrics_df

Model  Accuracy  Precision    Recall  F1-Score
0  Logistic Regression  0.965517        1.0  0.916667  0.956522

In [24]:
#classifier but margin classifier

# Initialize and train DecisionTree Model
tree_clf = DecisionTreeClassifier(random_state=42)
tree_clf.fit(X_train, y_train)


metrics = {
    'Model': ['Decision Tree'],
    'Accuracy': [
                 accuracy_score(y_val, tree_clf.predict(X_val)),
                ],
    'Precision': [
                  precision_score(y_val, tree_clf.predict(X_val)),
                ],
    'Recall': [
               recall_score(y_val, tree_clf.predict(X_val)),
               ],
    'F1-Score': [
                 f1_score(y_val, tree_clf.predict(X_val)),
                 ]
}

metrics_df = pd.DataFrame(metrics)
metrics_df



Model  Accuracy  Precision    Recall  F1-Score
0  Decision Tree  0.931034   0.884615  0.958333      0.92

In [26]:
# Initialize and train SVM Model
svm_clf = SVC(random_state=42)
svm_clf.fit(X_train, y_train)

metrics = {
    'Model': ['SVM'],
    'Accuracy': [
                 accuracy_score(y_val, svm_clf.predict(X_val))],
    'Precision': [
                  precision_score(y_val, svm_clf.predict(X_val))],
    'Recall': [
               recall_score(y_val, svm_clf.predict(X_val))],
    'F1-Score': [
                 f1_score(y_val, svm_clf.predict(X_val))]
}

metrics_df = pd.DataFrame(metrics)
metrics_df

Model  Accuracy  Precision    Recall  F1-Score
0   SVM  0.913793        1.0  0.791667  0.883721

In [30]:
#Regression

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

filename = 'house-prices-advanced-regression-techniques.zip'
os.makedirs('regression', mode=0o777, exist_ok=True)
for root, dirs, file in os.walk("./", topdown=True):
    if filename in file:
        break
else:
    !kaggle competitions download -c house-prices-advanced-regression-techniques
    !mv house-prices-advanced-regression-techniques.zip regression/

Traceback (most recent call last):
  File "/Users/jahnavisk/Documents/TicTacToe-Hangman/env1/bin/kaggle", line 5, in <module>
    from kaggle.cli import main
  File "/Users/jahnavisk/Documents/TicTacToe-Hangman/env1/lib/python3.12/site-packages/kaggle/__init__.py", line 7, in <module>
    api.authenticate()
  File "/Users/jahnavisk/Documents/TicTacToe-Hangman/env1/lib/python3.12/site-packages/kaggle/api/kaggle_api_extended.py", line 407, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in /Users/jahnavisk/.kaggle. Or use the environment method. See setup instructions at https://github.com/Kaggle/kaggle-api/
mv: rename house-prices-advanced-regression-techniques.zip to regression/house-prices-advanced-regression-techniques.zip: No such file or directory


In [31]:
df = pd.read_csv("regression/train.csv")
df.head()



Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [32]:

# Define the target variable and features
target = 'SalePrice'
features = df.drop(columns=[target])
features.head()



Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC Fence MiscFeature  \
0         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   
1         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   
2         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   
3         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   
4         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      2    2008        WD         Normal  
1       0      5    2007        WD         Normal  
2       0      9    2008        WD         Normal  
3       0      2    2006        WD        Abnorml  
4       0     12    2008        WD         Normal  

[5 rows x 80 columns]

In [33]:
# Drop rows with missing target values
df = df.dropna(subset=[target])
df.isnull().sum()


Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [34]:
# drop columns with all NaN's
df = df.dropna(axis=1)
df.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotArea          0
Street           0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 62, dtype: int64

In [35]:
X = df.drop(columns=[target])
y = df[target]

# Identify numerical columns
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns

# Preprocess the data: scale numerical features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X[numerical_features])

In [36]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Initialize and train the Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [37]:
# Make predictions on the test set
y_pred = model.predict(X_test)
y_pred[:10]

array([157802.41787327, 309399.48082109, 114501.90493963, 179951.02492489,
       300262.88243212,  47433.05670254, 229972.10111009, 148364.20846544,
        43738.65448403, 152230.52522863])

In [38]:
# Calculate performance metrics
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [39]:
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R²): {r2:.2f}")

Mean Squared Error (MSE): 1393360414.44
R-squared (R²): 0.82


In [40]:
if r2 > 0.8:
    print("The model explains a high proportion of the variance in house prices, suggesting a strong fit.")
elif r2 > 0.5:
    print("The model explains a moderate proportion of the variance in house prices, indicating a reasonable fit.")
else:
    print("The model explains a low proportion of the variance in house prices, indicating that it may not fit the data well.")

The model explains a high proportion of the variance in house prices, suggesting a strong fit.


In [ ]:
'''
Tasks
1. Perform min-max scaling on a these set of values [171, 120, 86, 176, 77]. The input values range from 32 to 212 and the output should range from
0 to 100.
2. Perform standardization (2-score normalization) on a dataset with the following values: [50, 60, 70, 89, 901. Ensure the transformed values have a mean of 0 and a standard deviation of 1.
3. Convert the categorical labels ['cat', 'dog', 'fish', 'cat', 'doz'1 into numerical labels using label encoding.
4. Apply one-hot encoding to the categorical variable ['apple', 'banana", "orange", "banana", "banana", "apple", orange", "orange"].
5. Split the dataset X - [[1], [2], [3], [4], [5], [6), [71, [811 and y - [10, 20, 30, 40, 50, 69, 70, 89] into training and testing sets with a test size of 25%.
6. Generate a confusion matrix for the true labels [1, 0, 1, 1, 0] and the predicted labels [1, 0, 0, 1, 1]
7. Train a random forest model on the breast-cancer dataset and output the importance of each feature.
8. Train a support vector regression model on the house-pricing dataset and check if the model performs better than the linear regression model.

'''

In [43]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

values = [171,120,86,176,77]

values = np.array([171, 120, 86, 176, 77]).reshape(-1, 1)
scaler = MinMaxScaler(feature_range=(0, 100))
scaled_values = scaler.fit_transform(values)

print(scaled_values.flatten())


[ 94.94949495  43.43434343   9.09090909 100.           0.        ]


In [44]:
from sklearn.preprocessing import StandardScaler
import numpy as np

values = np.array([50, 60, 70, 89, 901]).reshape(-1, 1)
scaler = StandardScaler()
standardized_values = scaler.fit_transform(values)
mean = np.mean(standardized_values)
sd = np.std(standardized_values)
print("mean",mean)
print("standard deviation",sd)
print(standardized_values.flatten())

mean 4.4408920985006264e-17
standard deviation 1.0
[-0.5513125  -0.52134987 -0.49138723 -0.43445822  1.99850782]


In [45]:
from sklearn.preprocessing import LabelEncoder

# Define the categorical labels
labels = ['cat', 'dog', 'fish', 'cat', 'doz']

# Create an instance of LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the labels
encoded_labels = label_encoder.fit_transform(labels)

print(encoded_labels)

[0 1 3 0 2]


In [46]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Define the categorical labels
labels = ['apple', 'banana', 'orange', 'banana', 'banana', 'apple', 'orange', 'orange']

# Create an instance of OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# Fit and transform the labels
encoded_labels = encoder.fit_transform(np.array(labels).reshape(-1, 1))

print(encoded_labels)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [47]:
from sklearn.model_selection import train_test_split
import numpy as np

# Define the dataset
X = np.array([[1], [2], [3], [4], [5], [6], [7], [8]])
y = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Split the dataset into training and testing sets with a test size of 25%
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size=0.25, random_state=42)

print("X_train:", X_train1)
print("X_test:", X_test1)
print("y_train:", y_train1)
print("y_test:", y_test1)

X_train: [[1]
 [8]
 [3]
 [5]
 [4]
 [7]]
X_test: [[2]
 [6]]
y_train: [10 80 30 50 40 70]
y_test: [20 60]


In [48]:
from sklearn.metrics import confusion_matrix

# Define the true and predicted labels
true_labels = [1, 0, 1, 1, 0]
predicted_labels = [1, 0, 0, 1, 1]

# Generate the confusion matrix
confusion_mat = confusion_matrix(true_labels, predicted_labels)

print(confusion_mat)

[[1 1]
 [1 2]]


In [51]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [58]:
data = "./classification/data.csv"
df = pd.read_csv(data)

df = df.drop(['Unnamed: 32', 'id'], axis = 1)

#Change M to 1, B to 0 in diagnosis column

X = df.drop('diagnosis', axis=1)  
y = df['diagnosis']     

# Convert 'diagnosis' column to binary
y = y.replace({'M': 1, 'B': 0})

from sklearn.model_selection import train_test_split

# Split the data into training, validation, and test sets (70%, 10%, 20%)
# Data split 70-30 as training and temp. the 30% of temp is further split to validation and test
#random state can be anything
#X is attribute, y is label
# either validatoin or test can be used for testing in this case but usually only test
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.66, random_state=42)

# Check the shapes of the splits
X_train.shape, X_val.shape, X_test.shape

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

metrics = {
    'Model': ['Random Forest'],
    'Accuracy': [
                 accuracy_score(y_val, rf.predict(X_val)),
                ],
    'Precision': [
                  precision_score(y_val, rf.predict(X_val)),
                ],
    'Recall': [
               recall_score(y_val, rf.predict(X_val)),
               ],
    'F1-Score': [
                 f1_score(y_val, rf.predict(X_val)),
                 ]
}

metrics_df = pd.DataFrame(metrics)
metrics_df

/var/folders/xz/6390rdvs3974jqvyrm7x_kqm0000gn/T/ipykernel_98221/3758475285.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = y.replace({'M': 1, 'B': 0})


Model  Accuracy  Precision    Recall  F1-Score
0  Random Forest  0.948276   0.956522  0.916667   0.93617

In [74]:
# #8
# df = pd.read_csv("regression/train.csv")

# target = 'SalePrice'
# features = df.drop(columns=[target])
# df = df.dropna(subset=[target])
# df = df.dropna(axis=1)
# df.isnull().sum()

In [68]:
# X = df.drop(columns=[target])
# y = df[target]

# # Identify numerical columns
# numerical_features = X.select_dtypes(include=['int64', 'float64']).columns

# # Preprocess the data: scale numerical features
# scaler = StandardScaler()
# X_scaled = scaler.fit_transform(X[numerical_features])



In [75]:
# from sklearn.model_selection import train_test_split

# # Split the data into training, validation, and test sets (70%, 10%, 20%)
# # Data split 70-30 as training and temp. the 30% of temp is further split to validation and test
# #random state can be anything
# #X is attribute, y is label
# # either validatoin or test can be used for testing in this case but usually only test
# X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
# X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.66, random_state=42)

# # Check the shapes of the splits
# X_train.shape, X_val.shape, X_test.shape



In [76]:
# # Initialize and train SVM Model
# svm_clf = SVC(random_state=42)
# svm_clf.fit(X_train, y_train)

# metrics = {
#     'Model': ['SVM'],
#     'Accuracy': [
#                  accuracy_score(y_val, svm_clf.predict(X_val))],
#     'Precision': [
#                   precision_score(y_val, svm_clf.predict(X_val))],
#     'Recall': [
#                recall_score(y_val, svm_clf.predict(X_val))],
#     'F1-Score': [
#                  f1_score(y_val, svm_clf.predict(X_val))]
# }

# metrics_df = pd.DataFrame(metrics)
# metrics_df

In [73]:
#8

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

# Load the dataset
df = pd.read_csv("regression/train.csv")

# Define the target variable and features
target = 'SalePrice'
features = df.drop(columns=[target])

# Drop rows with missing target values
df = df.dropna(subset=[target])

# Drop columns with all NaN's
df = df.dropna(axis=1)

# Define the features and target
X = df.drop(columns=[target])
y = df[target]

# Identify numerical columns
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns

# Preprocess the data: scale numerical features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X[numerical_features])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Initialize and train the Linear Regression model
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
y_pred_linear = linear_model.predict(X_test)  # Add this line to get predictions

# Train a Support Vector Regression (SVR) model
svr_model = SVR(kernel='rbf')
svr_model.fit(X_train, y_train)
y_pred_svr = svr_model.predict(X_test)

# Evaluate the models
mse_linear = mean_squared_error(y_test, y_pred_linear)
mse_svr = mean_squared_error(y_test, y_pred_svr)

print(f"Linear Regression MSE: {mse_linear}")
print(f"Support Vector Regression MSE: {mse_svr}")

# Compare performances
if mse_svr < mse_linear:
    print("The SVR model performs better than the Linear Regression model.")
else:
    print("The Linear Regression model performs better than the SVR model.")

Linear Regression MSE: 1393360414.4419844
Support Vector Regression MSE: 7854592755.488554
The Linear Regression model performs better than the SVR model.
