In [1]:
import torch 
import numpy as np 
import math

In [38]:
#Directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [39]:
# From Numpy array
import numpy as np
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [40]:
# From other tensors
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8515, 0.7726],
        [0.5342, 0.2940]]) 



In [2]:
tensor=torch.rand(3,2)
print(tensor.device)

cpu


In [3]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Device tensor is noe stored on: {tensor.device}")
else:
    print("CUDA is not available. Tensor remains on CPU")

CUDA is not available. Tensor remains on CPU


In [4]:
tensor = torch.ones(4,4)
print(f"first row: {tensor[0]}","\n")
print(f"first column: {tensor[:,0]}","\n")
print(f"last column: {tensor[..., -1]}","\n")
tensor[:,1] = 0
print(tensor)

first row: tensor([1., 1., 1., 1.]) 

first column: tensor([1., 1., 1., 1.]) 

last column: tensor([1., 1., 1., 1.]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [6]:
ones=torch.zeros(2,2)+1
twos=torch.ones(2,2)*2
threes=(torch.ones(2,2)*7-1)/2
fours=twos**2
sqrt2s=twos**0.5

print(ones,"\n")
print(twos,"\n")
print(threes,"\n")
print(fours,"\n")
print(sqrt2s,"\n")

tensor([[1., 1.],
        [1., 1.]]) 

tensor([[2., 2.],
        [2., 2.]]) 

tensor([[3., 3.],
        [3., 3.]]) 

tensor([[4., 4.],
        [4., 4.]]) 

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]]) 



In [7]:
powers2=twos**torch.tensor([[1,2],[3,4]])
print(powers2,"\n")
fives=ones+fours
print(fives,"\n")
dozens=threes*fours
print(dozens,"\n")

tensor([[ 2.,  4.],
        [ 8., 16.]]) 

tensor([[5., 5.],
        [5., 5.]]) 

tensor([[12., 12.],
        [12., 12.]]) 



In [10]:
rand=torch.rand(2,4)
doubled=rand*(torch.ones(1,4)*2)
print(rand)
print(doubled)

tensor([[0.2717, 0.3851, 0.3082, 0.1363],
        [0.3478, 0.5445, 0.0838, 0.1843]])
tensor([[0.5433, 0.7702, 0.6164, 0.2726],
        [0.6955, 1.0891, 0.1675, 0.3687]])


In [12]:
a=torch.ones(4,3,2)
b=a*torch.rand(3,2)
print(b,"\n")
c=a*torch.rand(4,1,2)
print(c,"\n")
d=a*torch.rand(1,3,2)
print(d,"\n")

tensor([[[0.9913, 0.7130],
         [0.6616, 0.9126],
         [0.6919, 0.3287]],

        [[0.9913, 0.7130],
         [0.6616, 0.9126],
         [0.6919, 0.3287]],

        [[0.9913, 0.7130],
         [0.6616, 0.9126],
         [0.6919, 0.3287]],

        [[0.9913, 0.7130],
         [0.6616, 0.9126],
         [0.6919, 0.3287]]]) 

tensor([[[0.8303, 0.8397],
         [0.8303, 0.8397],
         [0.8303, 0.8397]],

        [[0.1924, 0.3589],
         [0.1924, 0.3589],
         [0.1924, 0.3589]],

        [[0.8884, 0.6669],
         [0.8884, 0.6669],
         [0.8884, 0.6669]],

        [[0.3571, 0.4259],
         [0.3571, 0.4259],
         [0.3571, 0.4259]]]) 

tensor([[[0.2552, 0.7286],
         [0.4095, 0.8665],
         [0.0446, 0.0863]],

        [[0.2552, 0.7286],
         [0.4095, 0.8665],
         [0.0446, 0.0863]],

        [[0.2552, 0.7286],
         [0.4095, 0.8665],
         [0.0446, 0.0863]],

        [[0.2552, 0.7286],
         [0.4095, 0.8665],
         [0.0446, 0.0863]]]) 

In [13]:
a=torch.rand(2,4)*2-1
print(torch.abs(a),"\n") #absolute val
print(torch.ceil(a),"\n") #ceiling
print(torch.floor(a),"\n") #floor
print(torch.clamp(a,-0.5,0.5),"\n")

tensor([[0.1814, 0.0931, 0.5596, 0.8865],
        [0.2700, 0.7118, 0.4675, 0.5981]]) 

tensor([[1., -0., -0., 1.],
        [1., -0., -0., -0.]]) 

tensor([[ 0., -1., -1.,  0.],
        [ 0., -1., -1., -1.]]) 

tensor([[ 0.1814, -0.0931, -0.5000,  0.5000],
        [ 0.2700, -0.5000, -0.4675, -0.5000]]) 



In [17]:
angles=torch.tensor([0,math.pi/4,math.pi/2,3*math.pi/4])
sines=torch.sin(angles)
arcsines=torch.asin(sines)
print( "sine and Arcsine:")
print(angles,"\n")
print(sines,"\n")
print(arcsines,"\n")

sine and Arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562]) 

tensor([0.0000, 0.7071, 1.0000, 0.7071]) 

tensor([0.0000, 0.7854, 1.5708, 0.7854]) 



In [16]:
b=torch.tensor([1,5,11])
c=torch.tensor([2,7,10])
print(torch.bitwise_xor(b,c))

tensor([3, 2, 1])


In [41]:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
print(d,"\n")
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(e,"\n")
print(torch.eq(d, e))  # returns a tensor of type bool



Broadcasted, element-wise equality comparison:
tensor([[1., 2.],
        [3., 4.]]) 

tensor([[1., 1.]]) 

tensor([[ True, False],
        [False, False]])


In [21]:
d= torch.tensor([[1.,2.],[3.,4.]])
print(torch.max(d))
# print(torch.max_item(d))
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1,2,1,2,1,2])))

tensor(4.)
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [42]:
v1 = torch.tensor([1., 0., 0.])  # x unit vector
v2 = torch.tensor([0., 1., 0.])  # y unit vector

print(torch.cross(v1, v2),"\n")  # returns cross product of vectors v1 and v2

m1 = torch.rand(2, 2)  # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]])  # three times identity matrix
print(m1,"\n")
m3 = torch.matmul(m1, m2)  # same as m3 = m1@m2
print(m3,"\n")
print(torch.svd(m3),"\n")  # singular value decomposition


tensor([0., 0., 1.]) 

tensor([[0.0721, 0.8304],
        [0.5713, 0.5208]]) 

tensor([[0.2163, 2.4913],
        [1.7140, 1.5625]]) 

torch.return_types.svd(
U=tensor([[-0.7423, -0.6701],
        [-0.6701,  0.7423]]),
S=tensor([3.1784, 1.2371]),
V=tensor([[-0.4119,  0.9112],
        [-0.9112, -0.4119]])) 



C:\Users\Janvii RV\AppData\Local\Temp\ipykernel_25984\3018723044.py:4: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Cross.cpp:66.)
  print(torch.cross(v1, v2),"\n")  # returns cross product of vectors v1 and v2


In [43]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))  # this operation creates a new tensor in memory
print(a)  # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)  # b has changed


a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [44]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)
print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)


Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.1632, 0.2528],
        [0.2333, 0.3847]])

After adding:
tensor([[1.1632, 1.2528],
        [1.2333, 1.3847]])
tensor([[1.1632, 1.2528],
        [1.2333, 1.3847]])
tensor([[0.1632, 0.2528],
        [0.2333, 0.3847]])

After multiplying
tensor([[0.0266, 0.0639],
        [0.0544, 0.1480]])
tensor([[0.0266, 0.0639],
        [0.0544, 0.1480]])


In [47]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)
print(c,"\n")
d = torch.matmul(a, b, out=c)
print(c,"\n") # contents of c have changed

assert c is d # test c & d are same object, not just containing equal values # make sure that our new c is the same object as the old one
assert id(c) == old_id

torch.rand(2, 2, out=c) # works for creation too!
print(c,"\n") # c has changed again

assert id(c) == old_id # still the same object!






tensor([[0., 0.],
        [0., 0.]]) 

tensor([[0.8719, 0.7835],
        [0.3472, 0.2158]]) 

tensor([[0.1633, 0.3165],
        [0.4645, 0.8172]]) 



In [48]:
a = torch.tensor([1, 2, 3, 4])
a_reshaped = torch.reshape(a, (2, 2))
print(a_reshaped,"\n")

b = torch.rand(56, 56)  # Consider 56x56 image
c = b.unsqueeze(0)  # unsqueeze(i) adds dimension of length 1 at index i
print(c,"\n")  # c is now a batch of 1 image of shape 56x56

d = torch.rand(1, 20)
print(d.shape,"\n")
e = d.squeeze(0)  # squeeze(i) removes a dimension if shape[i] is 1
print(e.shape,"\n")

x, y, z = torch.rand(2, 3), torch.rand(2, 3), torch.rand(2, 3)
cat_tensor = torch.cat((x, y, z), dim=0)  # concatenates tensors along rows
print(cat_tensor)


tensor([[1, 2],
        [3, 4]]) 

tensor([[[0.2921, 0.8717, 0.2719,  ..., 0.9897, 0.7270, 0.4055],
         [0.1525, 0.7066, 0.4651,  ..., 0.6802, 0.0283, 0.4640],
         [0.2021, 0.1674, 0.5078,  ..., 0.8106, 0.8377, 0.3742],
         ...,
         [0.5755, 0.2428, 0.8970,  ..., 0.2909, 0.4621, 0.9259],
         [0.0459, 0.6079, 0.3459,  ..., 0.7855, 0.8999, 0.5575],
         [0.9439, 0.6993, 0.2142,  ..., 0.1840, 0.6561, 0.4216]]]) 

torch.Size([1, 20]) 

torch.Size([20]) 

tensor([[0.9764, 0.8198, 0.3823],
        [0.5728, 0.6162, 0.7484],
        [0.1862, 0.4098, 0.8907],
        [0.0215, 0.0129, 0.9713],
        [0.2715, 0.7608, 0.7453],
        [0.7002, 0.1037, 0.6854]])


In [49]:
a = torch.ones(2, 2)
b=a
a[0][1] = 561 # we change a...
print(b) # ...and b is also altered


tensor([[  1., 561.],
        [  1.,   1.]])


In [50]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a # different objects in memory...
print(torch.eq(a,b)) # ...but still with the same contents!
a[0][1] = 561 # a changes...
print(b)   # ...but b is still all ones






tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


Questions:


In [15]:
#1. Obtain a tensor containing only zeros from the given tensor

pattern=torch.tensor([
    [1,1,1,1],
    [1,0,0,1],
    [1,0,0,1],
    [1,1,1,1]
])

zeros=torch.zeros_like(pattern)
print(zeros)


tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [14]:
#2. Create a Numpy array of shape (1,3,3) using PytTorch
np_array=torch.ones(3,3).numpy()
print(np_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# Create two random (2,2,2) tensors and find the max, min, mean, std of their product (matrix multiplication)

a=torch.rand(2,2,2)
b=torch.rand(2,2,2)
print(torch.max(torch.matmul(a,b)))
print(torch.min(torch.matmul(a,b)))
print(torch.mean(torch.matmul(a,b)))
print(torch.std(torch.matmul(a,b)))


tensor(1.0582)
tensor(0.1977)
tensor(0.5945)
tensor(0.3305)


In [26]:
#4.Convert a 16x16 tensor into a 1x256 tensor
a=torch.ones(16,16)
b=torch.reshape(a,(1,256))
print(b)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1.,

In [55]:
#5.Given twp tensors x and y,find the coefficients that best model the linear relationship Y = ax + b (Linear Regression)
x = torch.rand(10)
y = 2 * x + 1 + torch.randn(10) * 0.1

x_mean = torch.mean(x)
y_mean = torch.mean(y)

b = torch.sum((x - x_mean) * (y - y_mean)) / torch.sum((x - x_mean) ** 2)
a = y_mean - b * x_mean

print(f"a: {a}\nb: {b}")


a: 0.9876007437705994
b: 1.9313138723373413


In [25]:
#6.Perform element-wise multiplication and addition on two 3x3 tensors
a=torch.rand(3,3)
b=torch.rand(3,3)

print(a*b)
print(a+b)


tensor([[0.1125, 0.1489, 0.0210],
        [0.5871, 0.0653, 0.1461],
        [0.1373, 0.0020, 0.0014]])
tensor([[0.7033, 0.9543, 0.3532],
        [1.5777, 0.5697, 0.7659],
        [0.9926, 0.1205, 0.4800]])


In [23]:
#7.Stack two 2x3 tensors along a new dimension
a=torch.rand(2,3)
b=torch.rand(2,3)

print(torch.stack((a,b),dim=0))


tensor([[[0.2516, 0.8967, 0.6381],
         [0.7095, 0.2973, 0.1784]],

        [[0.8898, 0.2732, 0.1199],
         [0.7296, 0.2945, 0.5746]]])


In [27]:
#8.Create a 1D tensor with values ranging from 0 to 9
a=torch.arange(10)
print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [28]:
#9. Perform operations on tensors of different shapes: 2x3 and 1x3 tensor using broadcasting
a=torch.rand(2,3)
b=torch.rand(1,3)

print(a*b)
print(a+b)

tensor([[0.2668, 0.5068, 0.1676],
        [0.2092, 0.2588, 0.1479]])
tensor([[1.0336, 1.4496, 0.9300],
        [0.9251, 1.0283, 0.8493]])


In [29]:
#10. Reshape a 1D tensor with 12 elements into a 3x4 matrix.  give answer without comments
a=torch.rand(12)
b=torch.reshape(a,(3,4))
print(b)

tensor([[0.4722, 0.0895, 0.3973, 0.1964],
        [0.2889, 0.9246, 0.7908, 0.4213],
        [0.7952, 0.4587, 0.7342, 0.3880]])
